### ISSUE TITLE
Updating causes kernell

### ISSUE THREAD

**Issue by AndersMad** [eswann/ClearScript.Installer#2]
Thanks for the contrib - I kicked out my own cumbersome compile, but after updating the ClearScript.Installer to 5.4.1 it causes multiple low level crash in w3wp.exe in KernelBase.dll

```
Unhandled exception at 0x00007FFB39778B9C (KernelBase.dll) in w3wp.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131604, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFB30B30000).
```

This is probably due to the ClearScript project base (https://clearscript.codeplex.com) - but since this is a reflection of that, I'd thought I let you know / warn. Any one else got this problem? Reverted to the prior DLL's and it's ok again..

**Comment by eswann** [comment]
OK, thanks for the input...any change you can add a test that demonstrates the issue?

**Comment by AndersMad** [comment]
Found the reason: The (my) settings values of MaxExecutableBytes and MaxNewSpaceBytes was to high - this caused the low-level crash. Works with the default values.

I raised them since it was opposite in earlier versions - a big js file would crash it then.
